# Site settings
title: Systems Engineering Design
email: 
description: > # this means to ignore newlines until "baseurl:"
  The SED Group homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://systemsengineering.design" # the base hostname & protocol for your site

twitter_username: SED_Lab
github_username: sed-group
linkedin_username: systems-engineering-design-laboratory

# Build settings
markdown: kramdown
